// 014 A Gooey Marquee · A Gooey Marquee · CodePen，源 example/effect/014-a-gooey.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "014",
  name: "014 A Gooey Marquee",
  src: "A Gooey Marquee · CodePen",
  css: "\n.fx-014 .bl-wrap {\n  background-color: #000;\n  color: #fff;\n  font-size: 24px;\n}\n.fx-014 .marquee {\n  position: relative;\n  width: 100%;\n  height: 2em;\n  font-size: 5em;\n  font-weight: 900;\n  display: grid;\n  place-items: center;\n  overflow: hidden;\n}\n.fx-014 .marquee_text {\n  position: absolute;\n  min-width: 100%;\n  white-space: nowrap;\n  animation: fx014-marquee 16s infinite linear;\n  animation-delay: calc(0s - var(--fx-t));\n}\n@keyframes fx014-marquee {\n  from { translate: 70%; }\n  to   { translate: -70%; }\n}\n.fx-014 .marquee_blur {\n  position: absolute;\n  inset: 0;\n  display: grid;\n  place-items: center;\n  background-color: black;\n  background-image: linear-gradient(to right, white, 1rem, transparent 50%), linear-gradient(to left, white, 1rem, transparent 50%);\n  filter: contrast(28);\n}\n.fx-014 .marquee_blur p {\n  filter: blur(0.10em);\n}\n.fx-014 .marquee_clear {\n  position: absolute;\n  inset: 0;\n  display: grid;\n  place-items: center;\n}\n\n/* === 修复黑屏 ===\n   引擎把 .bl-wrap 设为 width:max-content，但本特效内容全是 position:absolute，\n   max-content 宽度坍缩为 0 + overflow:hidden 把文字全裁掉 → 整屏黑。\n   这里给容器明确宽度；跑马灯是连续滚动，关掉引擎的逐字露出遮罩；\n   并恢复被引擎 background:transparent 清空、黏稠(contrast)所必需的实底色与边缘渐变。 */\n/* === 修复黑屏 ===\n   引擎把 .bl-wrap 设为 width:max-content，但本特效内容全是 position:absolute，\n   max-content 宽度坍缩为 0 + overflow:hidden 把文字全裁掉 → 整屏黑。\n   引擎的 VISUAL_OVERRIDE 拼在模块 css 之后，需用更高特异度(:host .bl-wrap)压过它。\n   跑马灯是连续滚动，关掉逐字露出遮罩；并恢复黏稠(contrast)所必需的实底色与边缘渐变。 */\n.fx-014 .bl-wrap {\n  width: 90vw !important;\n  max-width: 90vw !important;\n  -webkit-mask-image: none !important;\n          mask-image: none !important;\n}\n.fx-014 .marquee { width: 100%; }\n.fx-014 .marquee_blur {\n  background-color: #000 !important;\n  background-image: none !important;\n}\n/* 歌词很短、每行仅显示数秒，原 ±70% 行程会让文字整段滚出屏外（看似黑屏）。\n   让文字居中并收窄跑马灯行程，使短歌词始终可见，同时保留黏稠漂移。 */\n.fx-014 .marquee_text { text-align: center; }\n@keyframes fx014-marquee {\n  from { translate: 30%; }\n  to   { translate: -30%; }\n}\n",
  html: "<div class=\"marquee\">\n  <div class=\"marquee_blur\" aria-hidden=\"true\">\n    <p class=\"marquee_text\">{{LINE}}</p>\n  </div>\n  <div class=\"marquee_clear\">\n    <p class=\"marquee_text\">{{LINE}}</p>\n  </div>\n</div>",
  timeBase: "global",
};
