// 024 EAT SLEEP RAVE - 3D ROTATE · EAT SLEEP RAVE - 3D ROTATE · CodePen，源 example/effect/024-eat-sleep.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "024",
  name: "024 EAT SLEEP RAVE - 3D ROTATE",
  src: "EAT SLEEP RAVE - 3D ROTATE · CodePen",
  css: "\n.fx-024 .bl-wrap {\n  background-color: #222;\n  overflow: hidden;\n}\n.fx-024 .container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n.fx-024 .box {\n  transform-style: preserve-3d;\n  animation: fx024-animate3d 7s ease-in-out infinite alternate;\n  animation-delay: calc(0s - var(--fx-t));\n}\n.fx-024 .box span {\n  background: linear-gradient(90deg, rgba(0,0,0,.1), rgba(0,0,0,.5) 90%, transparent);\n  text-transform: uppercase;\n  line-height: 0.76em;\n  position: absolute;\n  color: #fff;\n  font-size: clamp(1.5rem, 3.5vw, 3.5em);\n  white-space: nowrap;\n  font-weight: bold;\n  padding: 0px 10px;\n  transform-style: preserve-3d;\n  text-shadow: 0 10px 15px rgba(0,0,0,.3);\n  transform: translate(-50%, -50%) rotateX(calc(var(--i) * 22.5deg)) translateZ(220px);\n}\n@keyframes fx024-animate3d {\n  0%   { transform: perspective(500px) rotateX(0deg) rotate(5deg); }\n  100% { transform: perspective(50px) rotateX(360deg) rotate(5deg); }\n}\n/* 修复黑屏:引擎将 .bl-wrap 设为 width:max-content,而所有 .box span 均为 position:absolute,\n   宽度坍缩为 0,基于 0 宽的引擎遮罩把内容全部遮没。去掉引擎遮罩并给容器明确尺寸;\n   .box 设为定位上下文,使绝对定位的 span 以 .box 中心(被 flex 居中)为锚点形成 3D 文字环。 */\n.fx-024 .bl-wrap {\n  width: 90vw !important; max-width: 90vw !important; height: 100% !important;\n  display: flex; align-items: center; justify-content: center;\n  -webkit-mask-image: none !important; mask-image: none !important;\n}\n/* 仅上下翻转(scaleY(-1)):背面环的 span 因 rotateX 越过 90° 呈上下颠倒(左右不反),\n   翻正后背面/环内一侧正向可读(代价:正面变上下颠倒,符合\"正面反、背面正\"取向)。 */\n.fx-024 .container { width: 100%; height: 100%; transform: scaleY(-1); }\n.fx-024 .box { position: relative; }\n\n.fx-024 .box span { transform: translate(-50%, -50%) rotateX(calc(var(--i) * 22.5deg)) translateZ(110px) !important; }",
  html: "<div class=\"container\">\n  <div class=\"box\">\n    <span style=\"--i: 1\">{{LINE}}</span>\n    <span style=\"--i: 2\">{{LINE}}</span>\n    <span style=\"--i: 3\">{{LINE}}</span>\n    <span style=\"--i: 4\">{{LINE}}</span>\n    <span style=\"--i: 5\">{{LINE}}</span>\n    <span style=\"--i: 6\">{{LINE}}</span>\n    <span style=\"--i: 7\">{{LINE}}</span>\n    <span style=\"--i: 8\">{{LINE}}</span>\n    <span style=\"--i: 9\">{{LINE}}</span>\n    <span style=\"--i: 10\">{{LINE}}</span>\n    <span style=\"--i: 11\">{{LINE}}</span>\n    <span style=\"--i: 12\">{{LINE}}</span>\n    <span style=\"--i: 13\">{{LINE}}</span>\n    <span style=\"--i: 14\">{{LINE}}</span>\n    <span style=\"--i: 15\">{{LINE}}</span>\n    <span style=\"--i: 16\">{{LINE}}</span>\n  </div>\n</div>",
  timeBase: "line",
};
