// 027 Text shadow animation (CSS) but I'm being extra · Text shadow animation (CSS) but I'm being extra · CodePen，源 example/effect/027-css-text.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "027",
  name: "027 Text shadow animation (CSS) but I'm being extra",
  src: "Text shadow animation (CSS) but I'm being extra · CodePen",
  css: ".fx-027 {\n  --background: #f3a683;\n  --base: #303952;\n  --accent: #786fa6;\n  --shadow: #e77f67;\n}\n\n.fx-027 .bl-wrap {\n  background: var(--background);\n}\n\n.fx-027 .cool {\n  font: bold 3rem/1.2 sans-serif;\n  max-width: 20rem;\n}\n.fx-027 .cool .ch {\n  color: var(--shadow);\n  display: inline-block;\n  position: relative;\n  /* 按歌词时间逐字符显示:字符 i 在 reveal>i/n 即自身 start 时刻出现 */\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}\n@media (prefers-reduced-motion) {\n  .fx-027 .cool .ch {\n    color: var(--base);\n  }\n}\n.fx-027 .cool .ch::before {\n  -webkit-animation: fx027-max-height 0.4s cubic-bezier(0.61, 1, 0.88, 1) 1 normal both;\n  animation-delay: calc(0s - var(--fx-t));\n          animation: fx027-max-height 0.4s cubic-bezier(0.61, 1, 0.88, 1) 1 normal both;\n          animation-delay: calc(0s - var(--fx-t));\n  animation-delay: calc(calc(var(--i) * 0.1s) - var(--fx-t));\n  color: var(--accent);\n}\n.fx-027 .cool .ch::after {\n  -webkit-animation: fx027-max-width 0.7s cubic-bezier(0.61, 1, 0.88, 1) 1 normal both;\n  animation-delay: calc(0s - var(--fx-t));\n          animation: fx027-max-width 0.7s cubic-bezier(0.61, 1, 0.88, 1) 1 normal both;\n          animation-delay: calc(0s - var(--fx-t));\n  animation-delay: calc(calc(var(--i) * 0.1s) - var(--fx-t));\n  color: var(--base);\n}\n.fx-027 .cool .ch::before,.fx-027  .cool .ch::after {\n  content: attr(data-ch);\n  left: 0;\n  overflow: hidden;\n  position: absolute;\n  speak: none;\n}\n@media (prefers-reduced-motion) {\n  .fx-027 .cool .ch::before,.fx-027  .cool .ch::after {\n    -webkit-animation: none;\n    animation-delay: calc(0s - var(--fx-t));\n            animation: none;\n            animation-delay: calc(0s - var(--fx-t));\n    content: \"\";\n  }\n}\n\n@-webkit-keyframes fx027-max-width {\n  from {\n    max-width: 0;\n  }\n  to {\n    max-width: 100%;\n  }\n}\n\n@keyframes fx027-max-width {\n  from {\n    max-width: 0;\n  }\n  to {\n    max-width: 100%;\n  }\n}\n@-webkit-keyframes fx027-max-height {\n  from {\n    max-height: 0;\n  }\n  to {\n    max-height: 100%;\n  }\n}\n@keyframes fx027-max-height {\n  from {\n    max-height: 0;\n  }\n  to {\n    max-height: 100%;\n  }\n}\n/* 取消引擎按 --reveal 的遮罩露出(与字幕不同步),改用上面的逐字符显示 */\n.fx-027 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }",
  html: "<p class=\"cool\">{{LETTERS}}</p>",
  letterTpl: "<span class=\"ch\" data-ch=\"{ch}\" style=\"--i:{i};--n:{n}\">{ch}</span>",
  timeBase: "line",
};
