// 028 Holographic type · Holographic type · CodePen，源 example/effect/028-holographic-type.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "028",
  name: "028 Holographic type",
  src: "Holographic type · CodePen",
  css: ".fx-028 .bl-wrap {\n  font-size: 5em;\n  font-weight: 800;\n  background: linear-gradient(135deg, #eee, #ccc);\n}\n\n.fx-028 section {\n  position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  width: 400px;\n  height: 310px;\n  animation-duration: 2s;\n  animation-name: fx028-cube-rotate;\n  animation-iteration-count: infinite;\n  animation-direction: alternate;\n  animation-timing-function: ease-in-out;\n}\n\n.fx-028 .isolate {\n  isolation: isolate;\n  position: absolute;\n  top: 0;\n  height: 100%;\n  width: 100%;\n}\n\n@keyframes fx028-cube-rotate {\n  from {\n    transform: perspective(600px) rotate3d(0.6, 0.05, 0.2, 0deg);\n  }\n  to {\n    transform: perspective(600px) rotate3d(0.6, 0.05, 0.2, 20deg);\n  }\n}\n\n@keyframes fx028-shimmer {\n  from {\n    filter: contrast(190%) brightness(500%);\n  }\n  to {\n    filter: contrast(190%) brightness(130%);\n  }\n}\n\n.fx-028 .noise {\n  width: 100%;\n  height: 100%;\n  padding: 8px;\n  background: linear-gradient(24deg, rgba(50, 0, 255, 0.1), CornflowerBlue), url(\"data:image/svg+xml,%3Csvg viewBox='0 0 400 310' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.55' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\");\n  background-clip: text;\n  -webkit-background-clip: text;\n  color: transparent;\n  animation-duration: 2s;\n  animation-name: fx028-shimmer;\n  animation-iteration-count: infinite;\n  animation-direction: alternate;\n}\n\n.fx-028 .overlay {\n  position: absolute;\n  top: 0;\n  width: 100%;\n  height: 100%;\n  background: antiquewhite;\n  mix-blend-mode: multiply;\n}\n\n@media all and (-webkit-min-device-pixel-ratio:0) and (min-resolution: .001dpcm) {\n  .fx-028 .overlay {\n    opacity: 0.6;\n  }\n}\n/* 逐字全息:每字各自把噪点+渐变 clip 进字形(用 :host 盖过 VISUAL_OVERRIDE 的\n   background:transparent / fill:green),并按歌词时间逐字符出现。父级 .noise 的\n   shimmer 滤镜仍作用于这些 span。 */\n.fx-028 .nl {\n  display: inline-block;\n  background: linear-gradient(24deg, rgba(50, 0, 255, 0.1), CornflowerBlue), url(\"data:image/svg+xml,%3Csvg viewBox='0 0 400 310' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.55' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\") !important;\n  background-clip: text !important;\n  -webkit-background-clip: text !important;\n  color: transparent !important;\n  -webkit-text-fill-color: transparent !important;\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}\n/* 取消引擎按 --reveal 的遮罩露出(会把字从中间切断),改用上面的逐字符显示 */\n.fx-028 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }",
  html: "<section>\n  <div class=\"isolate\">\n    <div class=\"noise\">{{LETTERS}}</div>\n    <div class=\"overlay\"></div>\n  </div>\n</section>",
  letterTpl: "<span class=\"nl\" style=\"--i:{i}; --n:{n}\">{ch}</span>",
  timeBase: "line",
};
