// 029 Text Animation · Text Animation · CodePen，源 example/effect/029-text-animation-2.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "029",
  name: "029 Text Animation",
  src: "Text Animation · CodePen",
  css: "@font-face {\n  src: url(\"https://www.axis-praxis.org/fonts/webfonts/AvenirNext_Variable.woff2\") format(\"woff2\");\n  font-style: normal;\n  font-weight: normal;\n}\n.fx-029 .bl-wrap {\n  background-color: black;\n  color: transparent;\n}\n\n.fx-029 .text {\n  font-variation-settings: \"wght\" 400, \"wdth\" 100;\n  font-size: 10em;\n  text-align: center;\n  position: absolute;\n  animation: fx029-text-flow 6s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-029 .text:nth-child(1) {\n  animation-delay: calc(0.25s - var(--fx-t));\n  opacity: 0.9;\n  -webkit-text-stroke: 3px #ffb3c0;\n  z-index: 0;\n}\n\n.fx-029 .text:nth-child(2) {\n  animation-delay: calc(0.5s - var(--fx-t));\n  opacity: 0.8;\n  -webkit-text-stroke: 3px #ffa7b6;\n  z-index: -1;\n}\n\n.fx-029 .text:nth-child(3) {\n  animation-delay: calc(0.75s - var(--fx-t));\n  opacity: 0.7;\n  -webkit-text-stroke: 3px #ff9aab;\n  z-index: -2;\n}\n\n.fx-029 .text:nth-child(4) {\n  animation-delay: calc(1s - var(--fx-t));\n  opacity: 0.6;\n  -webkit-text-stroke: 3px #ff8da1;\n  z-index: -3;\n}\n\n.fx-029 .text:nth-child(5) {\n  animation-delay: calc(1.25s - var(--fx-t));\n  opacity: 0.5;\n  -webkit-text-stroke: 3px #ff8096;\n  z-index: -4;\n}\n\n.fx-029 .text:nth-child(6) {\n  animation-delay: calc(1.5s - var(--fx-t));\n  opacity: 0.4;\n  -webkit-text-stroke: 3px #ff748c;\n  z-index: -5;\n}\n\n.fx-029 .text:nth-child(7) {\n  animation-delay: calc(1.75s - var(--fx-t));\n  opacity: 0.3;\n  -webkit-text-stroke: 3px #ff6781;\n  z-index: -6;\n}\n\n.fx-029 .text:nth-child(8) {\n  animation-delay: calc(2s - var(--fx-t));\n  opacity: 0.2;\n  -webkit-text-stroke: 3px #ff5a77;\n  z-index: -7;\n}\n\n.fx-029 .text:nth-child(9) {\n  animation-delay: calc(2.25s - var(--fx-t));\n  opacity: 0.1;\n  -webkit-text-stroke: 3px #ff4d6c;\n  z-index: -8;\n}\n\n@keyframes fx029-text-flow {\n  25% {\n    font-variation-settings: \"wght\" 900, \"wdth\" 100;\n    filter: hue-rotate(0deg);\n  }\n  50% {\n    transform: translateY(-100px);\n    font-variation-settings: \"wght\" 400, \"wdth\" 100;\n  }\n  75% {\n    transform: translateY(0%);\n    font-variation-settings: \"wght\" 900, \"wdth\" 100;\n    filter: hue-rotate(90deg);\n  }\n}\n/* 修复黑屏:9 层 .text 全为 position:absolute,引擎 .bl-wrap{width:max-content}\n   坍缩为 0,导致按宽度的 reveal 遮罩宽 0 全遮 → 黑屏。给容器明确宽度并去遮罩。 */\n.fx-029 .bl-wrap {\n  position: relative;\n  width: 90vw !important;\n  max-width: 90vw !important;\n  -webkit-mask-image: none !important;\n          mask-image: none !important;\n}\n.fx-029 .text { left: 0; right: 0; }\n/* 保留\"描边回声\"本貌:透明填充只留各层彩色描边(盖过 VISUAL_OVERRIDE 的 fill:green) */\n.fx-029 .text,.fx-029 .text * {\n  color: transparent !important;\n  -webkit-text-fill-color: transparent !important;\n}\n/* 按歌词时间逐字符出现(与各层回声透明度相乘);所有 9 层同一 --i/--n 同步揭示 */\n.fx-029 .tl {\n  display: inline-block;\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}",
  html: "<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>\n<div class=\"text\">{{LETTERS}}</div>",
  letterTpl: "<span class=\"tl\" style=\"--i:{i}; --n:{n}\">{ch}</span>",
  timeBase: "line",
};
