// 032 Pure CSS text-animation · Pure CSS text-animation · CodePen，源 example/effect/032-pure-css-2.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "032",
  name: "032 Pure CSS text-animation",
  src: "Pure CSS text-animation · CodePen",
  css: ".fx-032 .bl-wrap {\n  background: black;\n  color: tomato;\n}\n\n.fx-032 .jt {\n  position: relative;\n  font-size: 20vmin;\n  text-transform: uppercase;\n  font-display: swap;\n  text-shadow: 0 0 10px tomato;\n}\n\n.fx-032 .jt__row {\n  display: block;\n}\n.fx-032 .jt__row:nth-child(1) {\n  clip-path: polygon(-10% 75%, 110% 75%, 110% 110%, -10% 110%);\n}\n.fx-032 .jt__row:nth-child(2) {\n  clip-path: polygon(-10% 50%, 110% 50%, 110% 75.3%, -10% 75.3%);\n}\n.fx-032 .jt__row:nth-child(3) {\n  clip-path: polygon(-10% 25%, 110% 25%, 110% 50.3%, -10% 50.3%);\n}\n.fx-032 .jt__row:nth-child(4) {\n  clip-path: polygon(-10% 0%, 110% 0%, 110% 25.3%, -10% 25.3%);\n}\n\n.fx-032 .jt__row.jt__row--sibling {\n  position: absolute;\n  top: 0;\n  left: 0;\n  user-select: none;\n}\n\n.fx-032 .jt__text {\n  display: block;\n  transform-origin: bottom left;\n  animation: fx032-moveIn 2s 0s cubic-bezier(.36,0,.06,1) alternate infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n.fx-032 .jt__row:nth-child(1) .jt__text {\n  transform: translateY(-0.1em);\n}\n.fx-032 .jt__row:nth-child(2) .jt__text {\n  transform: translateY(-0.3em) scaleY(1.1);\n}\n.fx-032 .jt__row:nth-child(3) .jt__text {\n  transform: translateY(-0.5em) scaleY(1.2);\n}\n.fx-032 .jt__row:nth-child(4) .jt__text {\n  transform: translateY(-0.7em) scaleY(1.3);\n}\n\n@keyframes fx032-moveIn {\n  50%, 100% {\n    transform: translateY(0em)\n  }\n  0% {\n    opacity: 0;\n    filter: blur(10px);\n  }\n  100% {\n    opacity: 1;\n    filter: blur(0px);\n  }\n}\n/* 按歌词时间逐字符出现(与 .jt__text 的 moveIn 脉动相乘);4 个切片行同一 --i/--n 同步揭示 */\n.fx-032 .jl {\n  display: inline-block;\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}\n/* 取消引擎按 --reveal 的遮罩露出(与字幕不同步),改用上面的逐字符显示;水平切片(clip-path)保留 */\n.fx-032 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }",
  html: "<h1 class=\"jt\">\n  <span class=\"jt__row\"><span class=\"jt__text\">{{LETTERS}}</span></span>\n  <span class=\"jt__row jt__row--sibling\" aria-hidden=\"true\"><span class=\"jt__text\">{{LETTERS}}</span></span>\n  <span class=\"jt__row jt__row--sibling\" aria-hidden=\"true\"><span class=\"jt__text\">{{LETTERS}}</span></span>\n  <span class=\"jt__row jt__row--sibling\" aria-hidden=\"true\"><span class=\"jt__text\">{{LETTERS}}</span></span>\n</h1>",
  letterTpl: "<span class=\"jl\" style=\"--i:{i}; --n:{n}\">{ch}</span>",
  timeBase: "line",
};
