// 034 Waaaves · Waaaves · CodePen，源 example/effect/034-waaaves.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "034",
  name: "034 Waaaves",
  src: "Waaaves · CodePen",
  css: ".fx-034 {\n  --lower: 100;\n  --upper: 700;\n}\n.fx-034 .bl-wrap {\n  background: #70c9db;\n  position: relative;\n  height: 100%;\n}\n\n.fx-034 h1.wave-layer {\n  font-size: 7rem;\n  text-align: center;\n  position: absolute;\n  top: 50%;\n  left: 50%;\n  white-space: nowrap;\n  transform: translate(-50%, -50%) translate(calc(var(--x, 0) * 1%), calc(var(--y, 0) * 1%));\n  font-variation-settings: 'wght' var(--lower);\n  margin: 0;\n}\n.fx-034 h1.wave-layer .ch {\n  -webkit-animation: fx034-rise 2.25s infinite ease-in-out;\n  animation-delay: calc(0s - var(--fx-t));\n          animation: fx034-rise 2.25s infinite ease-in-out;\n          animation-delay: calc(0s - var(--fx-t));\n  -webkit-animation-delay: calc(calc((var(--i) - 3) * 0.225s) - var(--fx-t));\n          animation-delay: calc(calc((var(--i) - 3) * 0.225s) - var(--fx-t));\n  display: inline-block;\n  /* 按歌词时间逐字符出现:字符 i 在 reveal>i/n 即自身 start 时刻显示 */\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}\n.fx-034 h1.wave-layer:nth-child(1) .ch {\n  color: hsla(180, 100%, 90%, 0.125);\n}\n.fx-034 h1.wave-layer:nth-child(2) .ch {\n  color: hsla(180, 100%, 90%, 0.25);\n}\n.fx-034 h1.wave-layer:nth-child(3) .ch {\n  color: hsla(180, 100%, 90%, 0.5);\n}\n@keyframes fx034-rise {\n  50% {\n    font-variation-settings: 'wght' var(--upper);\n    color: hsla(180, 100%, 100%, 1);\n    transform: translate(0, -15%);\n  }\n}\n/* 修复黑屏:3 层 .wave-layer 全为 position:absolute,引擎 .bl-wrap{width:max-content}\n   坍缩为 0,按宽度的 reveal 遮罩宽 0 全遮 → 黑屏。给容器明确宽高并去遮罩。 */\n.fx-034 .bl-wrap {\n  width: 90vw !important;\n  max-width: 90vw !important;\n  height: 100% !important;\n  -webkit-mask-image: none !important;\n          mask-image: none !important;\n}\n/* 还原 waaaves 分层景深:让填充跟随各层 color(否则被主题 fill:green 压成不透明,\n   三层重叠杂乱)。后层半透明、前层实色;rise 动画的 color 提亮仍生效。 */\n.fx-034 .wave-layer:nth-child(1) .ch { color: rgba(0, 230, 118, 0.18) !important; }\n.fx-034 .wave-layer:nth-child(2) .ch { color: rgba(0, 230, 118, 0.4) !important; }\n.fx-034 .wave-layer:nth-child(3) .ch { color: rgba(0, 230, 118, 1) !important; }\n.fx-034 .wave-layer .ch { -webkit-text-fill-color: currentColor !important; }",
  html: "<h1 class=\"wave-layer\" style=\"--x: 6; --y: -6;\">{{LETTERS}}</h1>\n<h1 class=\"wave-layer\" style=\"--x: 3; --y: -3;\">{{LETTERS}}</h1>\n<h1 class=\"wave-layer\">{{LETTERS}}</h1>",
  letterTpl: "<span class=\"ch\" style=\"--i:{i};--n:{n}\">{ch}</span>",
  timeBase: "line",
};
