// 035 Easy Animation · Easy Animation · CodePen，源 example/effect/035-easy-animation.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "035",
  name: "035 Easy Animation",
  src: "Easy Animation · CodePen",
  css: ".fx-035 .bl-wrap {\n  position: relative;\n}\n\n.fx-035 .hello {\n  position: absolute;\n  top: 50%;\n  left: 50%;\n  transform: translate(-50%, -50%);\n  font-size: 25vw;\n  -webkit-animation-name: fx035-wave;\n          animation-name: fx035-wave;\n  -webkit-animation-iteration-count: infinite;\n          animation-iteration-count: infinite;\n  -webkit-animation-timing-function: ease-in-out;\n          animation-timing-function: ease-in-out;\n  -webkit-text-stroke-width: 3px;\n  -webkit-text-stroke-color: black;\n}\n\n.fx-035 .hello:nth-of-type(1) {\n  color: #7c4dff;\n  -webkit-animation-duration: 2s;\n          animation-duration: 2s;\n  -webkit-animation-delay: calc(0.55s - var(--fx-t));\n          animation-delay: calc(0.55s - var(--fx-t));\n}\n\n.fx-035 .hello:nth-of-type(2) {\n  color: #0091ea;\n  -webkit-animation-duration: 2s;\n          animation-duration: 2s;\n  -webkit-animation-delay: calc(0.3s - var(--fx-t));\n          animation-delay: calc(0.3s - var(--fx-t));\n}\n\n.fx-035 .hello:nth-of-type(3) {\n  color: #ff9100;\n  -webkit-animation-duration: 2s;\n          animation-duration: 2s;\n  -webkit-animation-delay: calc(0.05s - var(--fx-t));\n          animation-delay: calc(0.05s - var(--fx-t));\n}\n\n.fx-035 .hello:nth-of-type(4) {\n  color: #ff1744;\n  -webkit-animation-duration: 2s;\n          animation-duration: 2s;\n  -webkit-animation-delay: calc(-0.2s - var(--fx-t));\n          animation-delay: calc(-0.2s - var(--fx-t));\n}\n\n@-webkit-keyframes fx035-wave {\n  40%, 50% {\n    transform: translate(-50%, -65%) scale(1.05);\n  }\n  0%, 90%, 100% {\n    transform: translate(-50%, -45%) scale(0.95);\n  }\n}\n\n@keyframes fx035-wave {\n  40%, 50% {\n    transform: translate(-50%, -65%) scale(1.05);\n  }\n  0%, 90%, 100% {\n    transform: translate(-50%, -45%) scale(0.95);\n  }\n}\n/* 修复黑屏:4 层 .hello 全为 position:absolute,引擎 .bl-wrap{width:max-content}\n   坍缩为 0,按宽度的 reveal 遮罩宽 0 全遮 → 黑屏。给容器明确宽高并去遮罩。 */\n.fx-035 .bl-wrap {\n  width: 90vw !important;\n  max-width: 90vw !important;\n  height: 100% !important;\n  -webkit-mask-image: none !important;\n          mask-image: none !important;\n}\n/* 还原四色叠字:颜色直接设到字符 .hl 上(否则 .hl 被主题 fill/color:green 直接命中,\n   从父级继承的颜色无效),并让填充跟随该 color */\n.fx-035 .hello:nth-of-type(1) .hl { color: #7c4dff !important; }\n.fx-035 .hello:nth-of-type(2) .hl { color: #0091ea !important; }\n.fx-035 .hello:nth-of-type(3) .hl { color: #ff9100 !important; }\n.fx-035 .hello:nth-of-type(4) .hl { color: #ff1744 !important; }\n.fx-035 .hello .hl { -webkit-text-fill-color: currentColor !important; }\n/* 还原大字号(主题压成小字致 3px 黑描边糊成黑块);按需缩小一半 */\n.fx-035 .hello { font-size: clamp(24px, 7vw, 90px) !important; }\n.fx-035 .hello .hl { font-size: inherit !important; }\n/* 按歌词时间逐字符出现;4 层同一 --i/--n 同步揭示 */\n.fx-035 .hl {\n  display: inline-block;\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}",
  html: "<div class=\"hello\">{{LETTERS}}</div>\n<div class=\"hello\">{{LETTERS}}</div>\n<div class=\"hello\">{{LETTERS}}</div>\n<div class=\"hello\">{{LETTERS}}</div>",
  letterTpl: "<span class=\"hl\" style=\"--i:{i}; --n:{n}\">{ch}</span>",
  timeBase: "line",
};
