// 055 Metallic Bordered Text with CSS · Metallic Bordered Text with CSS · CodePen，源 example/effect/055-metallic-bordered.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "055",
  name: "055 Metallic Bordered Text with CSS",
  src: "Metallic Bordered Text with CSS · CodePen",
  css: ".fx-055 {\n  --gold: #ffb338;\n  --light-shadow: #77571d;\n  --dark-shadow: #3e2904;\n}\n\n.fx-055 .bl-wrap {\n  background: radial-gradient(#272727, #1b1b1b);\n  text-transform: uppercase;\n}\n\n.fx-055 .metallic-wrap {\n  display: grid;\n  grid-template-areas: 'overlap';\n  place-content: center;\n}\n\n.fx-055 .metallic-wrap > div {\n  background-clip: text;\n  -webkit-background-clip: text;\n  color: #363833;\n  font-weight: 900;\n  font-size: clamp(3em, 18vw, 10rem);\n  grid-area: overlap;\n  letter-spacing: 1px;\n  -webkit-text-stroke: 4px transparent;\n}\n\n.fx-055 .metallic-wrap .bg {\n  background-image: repeating-linear-gradient(105deg,\n    var(--gold) 0%,\n    var(--dark-shadow) 5%,\n    var(--gold) 12%);\n  color: transparent;\n  filter: drop-shadow(5px 15px 15px black);\n  transform: scaleY(1.05);\n  transform-origin: top;\n}\n\n.fx-055 .metallic-wrap .fg {\n  background-image: repeating-linear-gradient(5deg,\n    var(--gold) 0%,\n    var(--light-shadow) 23%,\n    var(--gold) 31%);\n  color: #1e2127;\n  transform: scale(1);\n}\n/* 用更高优先级(:host .bl-wrap .x = 0,3,0)覆盖顶层 VISUAL_OVERRIDE 的强制绿字,恢复金属渐变 */\n.fx-055 .bl-wrap .metallic-wrap .bg {\n  background-image: repeating-linear-gradient(105deg,\n    var(--gold) 0%, var(--dark-shadow) 5%, var(--gold) 12%) !important;\n  -webkit-background-clip: text !important;\n  background-clip: text !important;\n  color: transparent !important;\n  -webkit-text-fill-color: transparent !important;\n}\n.fx-055 .bl-wrap .metallic-wrap .fg {\n  background-image: repeating-linear-gradient(5deg,\n    var(--gold) 0%, var(--light-shadow) 23%, var(--gold) 31%) !important;\n  -webkit-background-clip: text !important;\n  background-clip: text !important;\n  color: #1e2127 !important;\n  -webkit-text-fill-color: #1e2127 !important;\n}\n/* 两层金属文字保持渐变连续,按 --reveal 裁切(CJK 等宽 => 恰好逐字步进露出) */\n.fx-055 .bl-wrap .metallic-wrap > div {\n  clip-path: inset(0 calc((1 - var(--reveal, 1)) * 100%) 0 0);\n}\n/* 取消引擎按 --reveal 的遮罩露出(与字幕不同步),改用上面的逐字裁切 */\n.fx-055 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }",
  html: "<div class=\"metallic-wrap\"><div class=\"bg\">{{LINE}}</div><div class=\"fg\">{{LINE}}</div></div>",
  timeBase: "line",
};
