// 060 DECONSTRUCTED · DECONSTRUCTED · CodePen，源 example/effect/060-deconstructed.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "060",
  name: "060 DECONSTRUCTED",
  src: "DECONSTRUCTED · CodePen",
  css: "\n.fx-060 .bl-wrap {\n  background-color: black;\n  overflow: hidden;\n}\n\n.fx-060 .deconstructed {\n  position: relative;\n  margin: auto;\n  height: 1.05em;\n  color: transparent;\n  font-size: 10vw;\n  font-weight: 700;\n  letter-spacing: -0.02em;\n  line-height: 1.05em;\n}\n\n.fx-060 .deconstructed > div {\n  position: absolute;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  color: #ffff64;\n  pointer-events: none;\n}\n\n.fx-060 .deconstructed > div:nth-child(1) {\n  -webkit-mask-image: linear-gradient(black 25%, transparent 25%);\n  mask-image: linear-gradient(black 25%, transparent 25%);\n  animation: fx060-deconstructed1 5s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-060 .deconstructed > div:nth-child(2) {\n  -webkit-mask-image: linear-gradient(transparent 25%, black 25%, black 50%, transparent 50%);\n  mask-image: linear-gradient(transparent 25%, black 25%, black 50%, transparent 50%);\n  animation: fx060-deconstructed2 5s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-060 .deconstructed > div:nth-child(3) {\n  -webkit-mask-image: linear-gradient(transparent 50%, black 50%, black 75%, transparent 75%);\n  mask-image: linear-gradient(transparent 50%, black 50%, black 75%, transparent 75%);\n  animation: fx060-deconstructed3 5s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-060 .deconstructed > div:nth-child(4) {\n  -webkit-mask-image: linear-gradient(transparent 75%, black 75%);\n  mask-image: linear-gradient(transparent 75%, black 75%);\n  animation: fx060-deconstructed4 5s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n@keyframes fx060-deconstructed1 {\n  0% { transform: translateX(100%); }\n  26% { transform: translateX(0%); }\n  83% { transform: translateX(-0.1%); }\n  100% { transform: translateX(-120%); }\n}\n\n@keyframes fx060-deconstructed2 {\n  0% { transform: translateX(100%); }\n  24% { transform: translateX(0.5%); }\n  82% { transform: translateX(-0.2%); }\n  100% { transform: translateX(-125%); }\n}\n\n@keyframes fx060-deconstructed3 {\n  0% { transform: translateX(100%); }\n  22% { transform: translateX(0%); }\n  81% { transform: translateX(0%); }\n  100% { transform: translateX(-130%); }\n}\n\n@keyframes fx060-deconstructed4 {\n  0% { transform: translateX(100%); }\n  20% { transform: translateX(0%); }\n  80% { transform: translateX(0%); }\n  100% { transform: translateX(-135%); }\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-060 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复颜色: 四层切片文字本应为黄色 #ffff64 */\n.fx-060 .bl-wrap .deconstructed > div {\n  color: #ffff64 !important;\n  -webkit-text-fill-color: #ffff64 !important;\n}\n",
  html: "<div class=\"deconstructed\">\n  {{LINE}}\n  <div>{{LINE}}</div>\n  <div>{{LINE}}</div>\n  <div>{{LINE}}</div>\n  <div>{{LINE}}</div>\n</div>",
  timeBase: "global",
};
