// 061 CSS Text Reveal · CSS Text Reveal · CodePen，源 example/effect/061-css-text-4.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "061",
  name: "061 CSS Text Reveal",
  src: "CSS Text Reveal · CodePen",
  css: "\n.fx-061 .bl-wrap {\n  background-color: #D8D8D8;\n  --bg-color: #D8D8D8;\n}\n\n.fx-061 .home-title {\n  font-size: 3em;\n  font-weight: normal;\n  color: #000;\n}\n\n.fx-061 .home-title span {\n  position: relative;\n  overflow: hidden;\n  display: block;\n  line-height: 1.2;\n}\n\n.fx-061 .home-title span::after {\n  content: '';\n  position: absolute;\n  top: 0;\n  right: 0;\n  width: 100%;\n  height: 100%;\n  background: white;\n  animation: fx061-a-ltr-after 2s cubic-bezier(.77,0,.18,1) forwards;\n  animation-delay: calc(0s - var(--fx-t));\n  transform: translateX(-101%);\n}\n\n.fx-061 .home-title span::before {\n  content: '';\n  position: absolute;\n  top: 0;\n  right: 0;\n  width: 100%;\n  height: 100%;\n  background: var(--bg-color);\n  animation: fx061-a-ltr-before 2s cubic-bezier(.77,0,.18,1) forwards;\n  animation-delay: calc(0s - var(--fx-t));\n  transform: translateX(0);\n}\n\n.fx-061 .home-title span:nth-of-type(1)::before,.fx-061 \n.home-title span:nth-of-type(1)::after {\n  animation-delay: calc(0.2s - var(--fx-t));\n}\n\n.fx-061 .home-title span:nth-of-type(2)::before,.fx-061 \n.home-title span:nth-of-type(2)::after {\n  animation-delay: calc(0.5s - var(--fx-t));\n}\n\n@keyframes fx061-a-ltr-after {\n  0% { transform: translateX(-100%); }\n  100% { transform: translateX(101%); }\n}\n\n@keyframes fx061-a-ltr-before {\n  0% { transform: translateX(0); }\n  100% { transform: translateX(200%); }\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-061 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复原始浅灰底,使黑字可见 */\n.fx-061 .bl-wrap {\n  background-color: #D8D8D8 !important;\n  --bg-color: #D8D8D8;\n  padding: 0.1em 0.3em !important;\n}\n\n/* 恢复原始颜色(黑色文字) */\n.fx-061 .bl-wrap .home-title,.fx-061 .bl-wrap .home-title .bl-char {\n  color: #000 !important;\n  -webkit-text-fill-color: #000 !important;\n}\n\n/* 逐字露出 */\n.fx-061 .bl-char {\n  display: inline-block;\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}\n\n/* 关闭原始擦除遮罩动画,避免覆盖逐字露出 */\n.fx-061 .bl-wrap .home-title span::before,.fx-061 .bl-wrap .home-title span::after {\n  display: none !important;\n}\n\n/* 字体在统一字号基础上缩小 30%(覆盖顶层 VISUAL_OVERRIDE 的强制 clamp 字号) */\n.fx-061 .bl-wrap .home-title,.fx-061 .bl-wrap .home-title span,.fx-061 .bl-wrap .home-title .bl-char {\n  font-size: calc(clamp(34px, 5vw, 88px) * 0.7) !important;\n}\n\n/* 内层 span 原为 display:block(配合原版逐行揭示),在引擎单行+逐字结构下会让每个\n   .bl-char 各占一行(竖排),英文长句尤其破碎。改 inline-block 让逐字横向排列。 */\n.fx-061 .bl-wrap .home-title span { display: inline-block !important; overflow: visible !important; white-space: nowrap !important; }\n",
  html: "<h1 class=\"home-title\">\n  <span>{{LETTERS}}</span>\n</h1>",
  letterTpl: "<span class=\"bl-char\" style=\"--i:{i};--n:{n}\">{ch}</span>",
  timeBase: "line",
};
