// 064 80s Fonts Text Effect 4: Cyberspace Text · 80s Fonts Text Effect 4: Cyberspace Text · CodePen，源 example/effect/064-80s-fonts.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "064",
  name: "064 80s Fonts Text Effect 4: Cyberspace Text",
  src: "80s Fonts Text Effect 4: Cyberspace Text · CodePen",
  css: ".fx-064 .bl-wrap {\n  background: radial-gradient(#050526 0%, #000000 90%) center center no-repeat black;\n  perspective: 340px;\n}\n\n.fx-064 .centered {\n  transform: rotateX(15deg);\n  text-align: center;\n}\n\n.fx-064 .cyberspace {\n  position: relative;\n  font-size: 4rem;\n  color: black;\n  -webkit-background-clip: text;\n  -webkit-text-fill-color: #87d1e4;\n  -webkit-text-stroke-width: 0.1rem;\n  -webkit-text-stroke-color: #87d1e4;\n  filter: url(#extrude);\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-064 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复颜色:实色填充 + 描边 (#87d1e4) */\n.fx-064 .bl-wrap .cyberspace {\n  color: black !important;\n  -webkit-text-fill-color: #87d1e4 !important;\n  -webkit-text-stroke-color: #87d1e4 !important;\n}\n\n/* 逐字露出 (clip-path 按 --reveal) */\n.fx-064 .bl-wrap .cyberspace {\n  clip-path: inset(0 calc((1 - var(--reveal, 1)) * 100%) 0 0);\n}",
  html: "<div class=\"centered\">\n  <span class=\"cyberspace\" data-text=\"{{LINE}}\">{{LINE}}</span>\n</div>\n<svg width=\"0\" height=\"0\" aria-hidden=\"true\">\n  <defs>\n    <filter id=\"extrude\">\n      <feMorphology operator=\"erode\" radius=\"0\" in=\"SourceGraphic\" result=\"erode\" />\n      <feMorphology operator=\"erode\" radius=\"2\" in=\"SourceGraphic\" result=\"erode1\" />\n      <feMorphology operator=\"erode\" radius=\"3\" in=\"SourceGraphic\" result=\"erode2\" />\n      <feMorphology operator=\"erode\" radius=\"4\" in=\"SourceGraphic\" result=\"erode3\" />\n      <feMorphology operator=\"erode\" radius=\"6\" in=\"SourceGraphic\" result=\"erode4\" />\n      <feComposite in=\"erode\" in2=\"erode1\" operator=\"out\" result=\"main\"/>\n      <feComposite in=\"erode1\" in2=\"erode2\" operator=\"out\" result=\"stroke1\"/>\n      <feComposite in=\"erode2\" in2=\"erode3\" operator=\"out\" result=\"stroke2\"/>\n      <feComposite in=\"erode3\" in2=\"erode4\" operator=\"out\" result=\"stroke3\"/>\n      <feGaussianBlur in=\"stroke1\" stdDeviation=\"0 10\" result=\"stroke1-blur\" />\n      <feBlend in=\"stroke1-blur\" mode=\"screen\" result=\"stroke1-blur-blend\"></feBlend>\n      <feGaussianBlur in=\"stroke2\" stdDeviation=\"0 10\" />\n      <feOffset dx=\"0\" dy=\"10\" result=\"stroke2-blur\"/>\n      <feBlend in=\"stroke2-blur\" mode=\"screen\" result=\"stroke2-blur-blend\"></feBlend>\n      <feGaussianBlur in=\"stroke3\" stdDeviation=\"0 25\" />\n      <feOffset dx=\"0\" dy=\"20\" result=\"stroke3-blur\"/>\n      <feBlend in=\"stroke3-blur\" mode=\"screen\" result=\"stroke3-blur-blend\"></feBlend>\n      <feFlood result=\"floodFill\" flood-color=\"rgba(0,0,0,0.7)\" flood-opacity=\"1\"/>\n      <feComposite in=\"floodFill\" in2=\"erode2\" operator=\"in\" result=\"black\"/>\n      <feBlend in=\"black\" mode=\"screen\" result=\"letterInside\"></feBlend>\n      <feMerge>\n        <feMergeNode in=\"stroke1-blur-blend\"></feMergeNode>\n        <feMergeNode in=\"stroke2-blur-blend\"></feMergeNode>\n        <feMergeNode in=\"stroke3-blur-blend\"></feMergeNode>\n        <feMergeNode in=\"main\"></feMergeNode>\n        <feMergeNode in=\"letterInside\"></feMergeNode>\n      </feMerge>\n    </filter>\n  </defs>\n</svg>",
  timeBase: "line",
};
