// 065 "HEY" - CSS 3D Text Animation · "HEY" - CSS 3D Text Animation [ANIMATION] · CodePen，源 example/effect/065-css-3d.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "065",
  name: "065 \"HEY\" - CSS 3D Text Animation",
  src: "\"HEY\" - CSS 3D Text Animation [ANIMATION] · CodePen",
  css: ".fx-065 {\n  --color-primary: #f6aca2;\n  --color-secondary: #f49b90;\n  --color-tertiary: #f28b7d;\n  --color-quaternary: #f07a6a;\n  --color-quinary: #ee6352;\n}\n\n.fx-065 .bl-wrap {\n  font-weight: 300;\n  font-size: 1.25rem;\n  background-color: #eff8e2;\n}\n\n.fx-065 .content {\n  display: flex;\n  align-content: center;\n  justify-content: center;\n}\n\n.fx-065 .text-shadows {\n  text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary), 9px 9px var(--color-quaternary), 12px 12px 0 var(--color-quinary);\n  font-weight: 400;\n  text-transform: uppercase;\n  font-size: calc(2rem + 5vw);\n  text-align: center;\n  margin: 0;\n  color: var(--color-primary);\n  animation: fx065-shadows 1.2s ease-in infinite;\n  animation-delay: calc(0s - var(--fx-t));\n  letter-spacing: 0.4rem;\n}\n\n@keyframes fx065-shadows {\n  0% {\n    text-shadow: none;\n  }\n  10% {\n    transform: translate(-3px, -3px);\n    text-shadow: 3px 3px 0 var(--color-secondary);\n  }\n  20% {\n    transform: translate(-6px, -6px);\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary);\n  }\n  30% {\n    transform: translate(-9px, -9px);\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary), 9px 9px var(--color-quaternary);\n  }\n  40% {\n    transform: translate(-12px, -12px);\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary), 9px 9px var(--color-quaternary), 12px 12px 0 var(--color-quinary);\n  }\n  50% {\n    transform: translate(-12px, -12px);\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary), 9px 9px var(--color-quaternary), 12px 12px 0 var(--color-quinary);\n  }\n  60% {\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary), 9px 9px var(--color-quaternary), 12px 12px 0 var(--color-quinary);\n  }\n  70% {\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary), 9px 9px var(--color-quaternary);\n  }\n  80% {\n    text-shadow: 3px 3px 0 var(--color-secondary), 6px 6px 0 var(--color-tertiary);\n  }\n  90% {\n    text-shadow: 3px 3px 0 var(--color-secondary);\n  }\n  100% {\n    text-shadow: none;\n  }\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-065 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复原始颜色 */\n.fx-065 .bl-wrap .text-shadows,.fx-065 .bl-wrap .text-shadows .bl-char {\n  color: #f6aca2 !important;\n  -webkit-text-fill-color: #f6aca2 !important;\n}\n\n/* 逐字露出 */\n.fx-065 .bl-char {\n  display: inline-block;\n  opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1);\n}",
  html: "<div class=\"content\"><h2 class=\"text-shadows\">{{LETTERS}}</h2></div>",
  letterTpl: "<span class=\"bl-char\" style=\"--i:{i};--n:{n}\">{ch}</span>",
  timeBase: "line",
};
