// 074 neon lights affect · neon lights affect · CodePen，源 example/effect/074-css-neon-2.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "074",
  name: "074 neon lights affect",
  src: "neon lights affect · CodePen",
  css: "\n@font-face {\n  src: url(https://dl.dropbox.com/s/df4zz9y6lmhocr9/England.otf?dl=0)\n}\n\n.fx-074 .bl-wrap {\n  background: black;\n  --lights: rgb(91, 235, 115);\n}\n\n.fx-074 #neon {\n  position: relative;\n  text-align: center;\n  font-size: 20vh;\n  color: white;\n  text-shadow: 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 1vh var(--lights);\n  animation: fx074-flicker240 7s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n  filter: brightness(1);\n}\n\n@keyframes fx074-flicker240 {\n  9% {\n    text-shadow: 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 1vh var(--lights);\n    filter: brightness(1);\n  }\n  10% {\n    text-shadow: none;\n    filter: brightness(.4);\n  }\n  11% {\n    text-shadow: 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 1vh var(--lights);\n    filter: brightness(1);\n  }\n  12% {\n    text-shadow: none;\n    filter: brightness(.4);\n  }\n  13% {\n    text-shadow: 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 1vh var(--lights);\n    filter: brightness(1);\n  }\n  66% {\n    text-shadow: 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 1vh var(--lights);\n    filter: brightness(1);\n  }\n  67% {\n    text-shadow: none;\n    filter: brightness(.4);\n  }\n  75% {\n    text-shadow: none;\n    filter: brightness(.4);\n  }\n  76% {\n    text-shadow: 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 .5vh var(--lights), 0 0 1vh var(--lights);\n    filter: brightness(1);\n  }\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-074 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复真实颜色: 白色字体 + 绿色霓虹光晕(text-shadow 未被覆盖) */\n.fx-074 .bl-wrap #neon,.fx-074 .bl-wrap #neon .bl-char {\n  color: white !important;\n  -webkit-text-fill-color: white !important;\n}\n\n/* 逐字露出 */\n.fx-074 .bl-char { display: inline-block; opacity: clamp(0, calc((var(--reveal, 1) - var(--i) / var(--n, 1)) * 1000), 1); }\n",
  html: "<div id=\"neon\">{{LETTERS}}</div>",
  letterTpl: "<span class=\"bl-char\" style=\"--i:{i};--n:{n}\">{ch}</span>",
  timeBase: "line",
};
