// 096 CSS Dashed Shadow · CSS Dashed Shadow · CodePen，源 example/effect/096-css-dashed.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "096",
  name: "096 CSS Dashed Shadow",
  src: "CSS Dashed Shadow · CodePen",
  css: "\n.fx-096 .bl-wrap {\n  font-size: 5vmin;\n  background-color: #e8e3c7;\n  text-align: center;\n  line-height: 1.4;\n}\n\n.fx-096 .dashed-shadow {\n  position: relative;\n  top: 8px;\n  left: 8px;\n  display: inline-block;\n  color: #ba9186;\n}\n\n@keyframes fx096-dash-animation {\n  0% { background-position: 0 0; }\n  100% { background-position: 100% 0; }\n}\n\n.fx-096 .dashed-shadow:before {\n  content: \" \";\n  display: block;\n  position: absolute;\n  top: -8px;\n  left: -8px;\n  bottom: -2px;\n  right: -2px;\n  z-index: 1;\n  background-image: linear-gradient(45deg, #e8e3c7 12.5%, rgba(232, 227, 199, 0) 12.5%, rgba(232, 227, 199, 0) 37.5%, #e8e3c7 37.5%, #e8e3c7 62.5%, rgba(232, 227, 199, 0) 62.5%, rgba(232, 227, 199, 0) 87.5%, #e8e3c7 87.5%);\n  background-size: 6px 6px;\n}\n\n.fx-096 .dashed-shadow:hover:before {\n  animation: fx096-dash-animation 30s infinite linear;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-096 .dashed-shadow:after {\n  z-index: 2;\n  content: attr(data-text);\n  position: absolute;\n  left: -8px;\n  top: -8px;\n  color: #b85b3f;\n  text-shadow: 3px 3px #e8e3c7;\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-096 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复颜色 */\n.fx-096 .bl-wrap .dashed-shadow { color: #ba9186 !important; -webkit-text-fill-color: #ba9186 !important; }\n\n/* 逐字露出 (PATTERN B clip-path) */\n.fx-096 .bl-wrap .dashed-shadow { clip-path: inset(0 calc((1 - var(--reveal, 1)) * 100%) 0 0); }\n\n.fx-096 .bl-wrap { background: transparent !important; }\n.fx-096 .dashed-shadow { top: 0 !important; left: 0 !important; color: #b85b3f !important; -webkit-text-fill-color: #b85b3f !important; text-shadow: 0.07em 0.07em #5c3a30 !important; }\n.fx-096 .dashed-shadow:before { display: none !important; }\n.fx-096 .dashed-shadow:after { display: none !important; }",
  html: "<div class=\"dashed-shadow\" data-text=\"{{LINE}}\">{{LINE}}</div>",
  timeBase: "line",
};
