// 097 Retro Glitch Effect Colors RGB · Retro Glitch Effect Colors RGB (Daily Design + Code #6) · CodePen，源 example/effect/097-retro-glitch.js，本文件由 convert-effects.mjs 生成
import type {VisualEffect} from '../../types';

export const effect: VisualEffect = {
  id: "097",
  name: "097 Retro Glitch Effect Colors RGB",
  src: "Retro Glitch Effect Colors RGB (Daily Design + Code #6) · CodePen",
  css: "\n.fx-097 {\n  --red: #FF0000;\n  --green: #00FF00;\n  --blue: #0000FF;\n}\n\n.fx-097 .bl-wrap {\n  background-color: #000000;\n  overflow: hidden;\n}\n\n.fx-097 .rgb-glitch {\n  position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  width: 100%;\n}\n\n.fx-097 .rgb-layer {\n  position: absolute;\n  font-size: 6vmin;\n  font-weight: 700;\n  text-transform: uppercase;\n  mix-blend-mode: screen;\n  white-space: nowrap;\n}\n\n.fx-097 .rgb-layer.layer-r {\n  color: var(--red);\n  transform: translate(4px, 4px);\n  animation: fx097-rgb-set1 1s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-097 .rgb-layer.layer-g {\n  color: var(--green);\n  transform: translate(0, 0);\n  animation: fx097-rgb-set2 1s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-097 .rgb-layer.layer-b {\n  color: var(--blue);\n  transform: translate(-4px, -4px);\n  animation: fx097-rgb-set3 1s infinite;\n  animation-delay: calc(0s - var(--fx-t));\n}\n\n.fx-097 .rgb-spacer {\n  font-size: 6vmin;\n  font-weight: 700;\n  text-transform: uppercase;\n  visibility: hidden;\n  white-space: nowrap;\n}\n\n@keyframes fx097-rgb-set1 {\n  0%   { transform: translate(4px, 4px); }\n  15%  { transform: translate(5px, 6px); }\n  30%  { transform: translate(4px, 4px); }\n  45%  { transform: translate(5px, 6px); }\n  60%  { transform: translate(4px, 4px); }\n  75%  { transform: translate(6px, -2px); }\n  100% { transform: translate(4px, 4px); }\n}\n\n@keyframes fx097-rgb-set2 {\n  0%   { transform: translate(0px, 0px); }\n  15%  { transform: translate(-1px, -2px); }\n  30%  { transform: translate(0px, 0px); }\n  45%  { transform: translate(-1px, -2px); }\n  60%  { transform: translate(0px, 0px); }\n  75%  { transform: translate(-1px, 1px); }\n  100% { transform: translate(0px, 0px); }\n}\n\n@keyframes fx097-rgb-set3 {\n  0%   { transform: translate(-4px, -4px); }\n  15%  { transform: translate(-6px, -6px); }\n  30%  { transform: translate(-4px, -4px); }\n  45%  { transform: translate(0px, 0px); }\n  60%  { transform: translate(-4px, -4px); }\n  75%  { transform: translate(-3px, -5px); }\n  100% { transform: translate(-4px, -4px); }\n}\n\n/* 取消引擎遮罩,改用逐字露出 */\n.fx-097 .bl-wrap { -webkit-mask-image: none !important; mask-image: none !important; }\n\n/* 恢复 RGB 三层原色 */\n.fx-097 .bl-wrap .rgb-layer.layer-r { color: var(--red) !important; -webkit-text-fill-color: var(--red) !important; }\n.fx-097 .bl-wrap .rgb-layer.layer-g { color: var(--green) !important; -webkit-text-fill-color: var(--green) !important; }\n.fx-097 .bl-wrap .rgb-layer.layer-b { color: var(--blue) !important; -webkit-text-fill-color: var(--blue) !important; }\n\n/* 逐字露出:对每个文字层做 clip-path */\n.fx-097 .bl-wrap .rgb-layer { clip-path: inset(0 calc((1 - var(--reveal, 1)) * 100%) 0 0); }\n",
  html: "<div class=\"rgb-glitch\">\n  <span class=\"rgb-layer layer-r\">{{LINE}}</span>\n  <span class=\"rgb-layer layer-g\">{{LINE}}</span>\n  <span class=\"rgb-layer layer-b\">{{LINE}}</span>\n  <span class=\"rgb-spacer\">{{LINE}}</span>\n</div>",
  timeBase: "line",
};
